### ISSUE TITLE
Upgrade flutter_map to 2.2.0

### ISSUE THREAD

**Issue by bmason8** [OwnWeb/flutter_map_tappable_polyline#47]
`Because flutter_map_tappable_polyline >=3.2.0 depends on flutter_map ^1.0.0 and fakeProject depends on flutter_map ^2.2.0, flutter_map_tappable_polyline >=3.2.0 is forbidden.`

Would be super helpful if this package could update it's flutter_map dependency to 2.2.0.

Thank you kindly.

**Comment by Cteq3132** [comment]
Hey, I had to use `flutter_map` v2.2.0 for a project and made a fork of this package that you can use to support v2.2.0 by adding the following lines in your `pubspec.yaml`:

```
flutter_map_tappable_polyline: 
    git:
      url: https://github.com/Cteq3132/flutter_map_tappable_polyline.git
      ref: chore/flutter-map-v2
```

I did not opened a PR for this because a version 3 of `flutter_map` is coming soon and a PR is already opened for this (#49).
