### ISSUE TITLE
Lines are flying away on  pinch rotation

### ISSUE THREAD

**Issue by MaxiStefan** [OwnWeb/flutter_map_tappable_polyline#61]
Basically title. I updated to the last version and whenever I rotate the map using a pinch motion  the lines drawn are flying away

**Comment by Arbimig** [comment]
Wrapping CustomPaint in MobileLayerTransformer in the flutter_map_tappable_polyline.dart file helped me

**Comment by lagivan** [comment]
@HugoHeneault the issue has been closed but the PR is still open. Could you please merge it? I've just come across the same issue and even created a new issue #64 before I've found this one.

**Comment by lagivan** [comment]
For now the solution can be applied using dependency overrides this way:
```
dependency_overrides:
  flutter_map_tappable_polyline:
    git:
      url: https://github.com/Camerash/flutter_map_tappable_polyline.git
      ref: 86eba4a8cd65dfa818b763a6cd6c0e961f00f466
```
